apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: coffee-ingress
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
spec:
    ingressClassName: alb
    rules:
        - http:
              paths:
                  - path: /customer/*
                    pathType: Prefix
                    backend:
                        service:
                            name: customer
                            port:
                                number: 8080
                  - path: /employee/*
                    pathType: Prefix
                    backend:
                        service:
                            name: employee
                            port:
                                number: 8080
