apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
    name: default
spec:
    template:
        spec:
            requirements:
                - key: kubernetes.io/arch
                  operator: In
                  values: ["amd64"]
                - key: kubernetes.io/os
                  operator: In
                  values: ["linux"]
                - key: karpenter.sh/capacity-type
                  operator: In
                  values: ["on-demand"]
                - key: node.kubernetes.io/instance-type
                  operator: In
                  values: ["t2.micro"]
            nodeClassRef:
                name: default
    limits:
        cpu: 1000
    disruption:
        consolidationPolicy: WhenUnderutilized
        expireAfter: 720h # 30 * 24h = 720h
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
    name: default
spec:
    amiFamily: AL2 # Amazon Linux 2
    role: "KarpenterNodeRole-coffee-supplier" # replace with your cluster name
    subnetSelectorTerms:
        - tags:
              karpenter.sh/discovery: "coffee-supplier" # replace with your cluster name
    securityGroupSelectorTerms:
        - tags:
              karpenter.sh/discovery: "coffee-supplier" # replace with your cluster name
