apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: customer-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: customer-hpa
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 30
