apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: customer
spec:
    replicas: 2
    selector:
        matchLabels:
            app: customer
    template:
        metadata:
            labels:
                app: customer
        spec:
            hostNetwork: true
            containers:
                - name: customer
                  image: $ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/customer
                  ports:
                      - containerPort: 8080
                        protocol: TCP
